Tasks api implementation
bmstu-iu9/ptp2022-8-todo-list pull request #101
Opened 2022-09-17 20:41 UTC by uma-op

Closes #42

2022-09-18 09:52 UTC, OkDenAl requested changes, later dismissed
Есть какие-то неочевидные поведения функций, лишние комментарии, лишние, на мой взгляд, фрагменты кода. В остальном норм, вроде

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/db/db.go
> +	1,  -- user_id
Зачем писать "--user_id" и тд? если ты это уже указывал

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/entity/task.go
> +	TaskId int64 `json:"-"`
А зачем 2 раза id ? и поему у TaskId в json "-"

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/api.go
> +	// TODO: auth check
проверка авторизации будет происходить через middleware слой, подобные TODO можно убрать

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/api.go
> +	if id == 0 {
а зачем это проверять? если в дальнейшем юзер с id=0 всё равно ошибку выдаст, а тут ещё и ошибку не выдает

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/api.go
> +	if user_id == 0 {
то же самое, писал выше

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/api.go
> +	if user_id == 0 {
и тут

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/api.go
> +	if user_id == 0 {
тут

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/api.go
> +	if user_id == 0 {
тут?

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/api_test.go
> +	// notFound := toJson(errors.Problem{Title: "Not found", Status: http.StatusNotFound})
комментарий бы убрать )

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/api_test.go
> +}
тут вообще не видел тестов с какими-то ошибками, можно добавить заведомо провальные кейсы, чтобы посмотреть как ошибки программа обрабатывает

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/repository.go
> +		if err != nil {
на ошибку надо проверить сразу после Scan

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/repository.go
> +	if err != nil {
тут тоже на ошибку как-то далековато проверяешь, просто если у тебя есть ошибка в Scan, то "task.CreatedOn = entity.Date(task_created_on)"  кнч выполнится, но это по большому счёту лишний код, change my mind

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/repository_test.go
> +}
тут как-то тоже случаи с ошибками не проверяются никак

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/service.go
> +	}
а зачем это дублировать? если в entity уже всё есть

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/service.go
> +type Service interface {
Отсутствуют dockstring`и

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/service.go
> +	if err != nil {
смысл? одного "return tasks, err" бы хватило

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/service.go
> +	if err != nil {
аналогично

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/service.go
> +	or := func(ss ...string) string {
что-то мне тут имена переменных не нравятся, как и название функции

2022-09-18 09:52 UTC, OkDenAl commented on backend/internal/tasks/repository.go
> +// labels with non zero id removes, and with zero creates
а почему именно такая логика? как-то не совсем очевидно, почему оно так работает

2022-09-18 09:54 UTC, geogreck commented on backend/internal/entity/task.go
> +	TaskId int64 `json:"-"`
Думаю это связано с тем, что у задач двойной айди, один для сервера и второй для клиента. Это сделано, чтобы всем было удобно. Однако логично, что серверный айди на клиент не передается

2022-09-18 10:04 UTC, uma-op commented on backend/internal/tasks/api.go
> +	if id == 0 {
Да, это просто заглушка для авторизации

2022-09-18 10:04 UTC, uma-op commented on backend/internal/tasks/api_test.go
> +	// notFound := toJson(errors.Problem{Title: "Not found", Status: http.StatusNotFound})
проглядел

2022-09-18 10:09 UTC, uma-op commented on backend/internal/tasks/repository.go
> +// labels with non zero id removes, and with zero creates
просто нужно было как-то удалять лейблы, а создавать новые запросы именно под эту цель мне не хотелось)

2022-09-18 10:10 UTC, uma-op commented on backend/internal/tasks/service.go
> +	}
тут определяется валидация для этих полей, я бы не смог определить методы для сущностей из другого пакета

2022-09-18 10:13 UTC, uma-op commented on backend/internal/tasks/service.go
> +	or := func(ss ...string) string {
функция называется так, потому что возвращает первую непустую строку (ну или пустую если таковых нет), а т.к. она взаимодействует со строками, то и переменные называются соответствующе

2022-09-18 10:16 UTC, uma-op commented on backend/internal/entity/task.go
> +	TaskId int64 `json:"-"`
> А зачем 2 раза id ? и поему у TaskId в json "-"

TaskId не передается в json так как лейблы передаются вместе с задачей, а id действительно добавлено для удобства

2022-09-18 10:20 UTC, uma-op commented on backend/internal/db/db.go
> +	1,  -- user_id
Просто комментарии чтобы видеть что есть что. В начале в этой строке было намного больше данных, поэтому такие комментарии помогали не запутаться

2022-09-18 15:17 UTC, stewkk commented on backend/internal/db/db.go
> +	1,  -- user_id
Годно кста

2022-09-18 15:21 UTC, stewkk commented on backend/internal/tasks/service.go
> +	if err != nil {
Тогда уж `return s.r.Get(user_id)` =)

2022-09-18 15:21 UTC, stewkk commented on backend/internal/tasks/service.go
> +	or := func(ss ...string) string {
Ну вообще мне тоже не нравятся названия

2022-09-18 21:11 UTC, stewkk requested changes

2022-09-18 21:11 UTC, stewkk commented on backend/internal/tasks/repository.go
> +
Тут забыл `defer rows.Close()`

2022-09-25 14:10 UTC, stewkk requested changes

2022-09-25 14:10 UTC, stewkk commented on backend/internal/db/migrations/1_initialize_schema.up.sql
> +	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
id должен генерироваться на стороне клиента

2022-09-25 14:10 UTC, stewkk commented on backend/internal/tasks/api.go
> +	task_id, err := strconv.Atoi(p.ByName("task_id"))
`task_id` - https://go.dev/doc/effective_go#names

2022-09-25 14:10 UTC, stewkk commented on backend/internal/tasks/repository_test.go
> +	{ // 0
Лучше в тест-кейсы включать их названия. Так проще искать упавший тест.

2022-09-25 14:23 UTC, stewkk requested changes

2022-09-25 14:23 UTC, stewkk commented on backend/internal/tasks/api.go
> +	mux.POST("/users/:user_id/tasks", accesslog.Log(errors.Handle(res.handlePost, res.logger), res.logger))
Создание задачи надо сделать через PUT (а также редактирование)

2022-09-25 14:24 UTC, stewkk commented on backend/internal/tasks/api.go
> +	mux.POST("/users/:user_id/tasks", accesslog.Log(errors.Handle(res.handlePost, res.logger), res.logger))
https://ptp.starovoytovai.ru/api/docs/

2022-09-25 15:06 UTC, Mazdaywik commented
Да, GitHub — соцсеть для программистов. Обсуждение на 37 реплик:

![image](https://user-images.githubusercontent.com/1309859/192150493-1e510cef-43e6-4a25-801f-e59536380708.png)

Круче здесь только #65.

2022-10-24 10:24 UTC, stewkk requested changes
Нужны небольшие правки!

2022-10-24 10:24 UTC, stewkk commented on backend/internal/db/migrations/1_initialize_schema.up.sql
> +	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Вынесено в #113

2022-10-24 10:24 UTC, stewkk commented on backend/internal/tasks/api.go
> +	}
Эту логику надо перенести в service (в `service.Set`), т.к. здесь нарушается принцип SRP - на апи навешивается дополнительная ответственность: определение типа запроса (перезапись или создание).

2022-10-24 10:24 UTC, stewkk commented on backend/internal/tasks/api.go
> +func (res *resource) handlePost(w http.ResponseWriter, r *http.Request, p httprouter.Params) error {
Название не очень.

2022-10-24 10:24 UTC, stewkk commented on backend/internal/tasks/api.go
> +	}
Это же лишний запрос?

2022-10-24 10:24 UTC, stewkk commented on backend/internal/tasks/repository.go
> +		task.DueDate = entity.Date(task_due_date)
А это обязательно делать?

2022-10-24 10:24 UTC, stewkk commented on backend/internal/tasks/service.go
> +	if *f == "" {
Почему?

2022-10-24 10:24 UTC, stewkk commented on backend/internal/tasks/service.go
> +	fmt.Println("st", t.Status.validate())
Стыдно!

2022-10-24 10:24 UTC, stewkk commented on backend/internal/tasks/service.go
> +	}
Запишем в техлдолг #117

2022-10-27 14:12 UTC, uma-op commented on backend/internal/tasks/api.go
> +	}
нет

2022-10-27 15:15 UTC, uma-op commented on backend/internal/tasks/repository.go
> +		task.DueDate = entity.Date(task_due_date)
да

2022-10-27 15:29 UTC, uma-op commented on backend/internal/tasks/service.go
> +	if *f == "" {
ой

2022-11-06 09:44 UTC, stewkk approved these changes

2022-11-06 09:45 UTC, stewkk commented
@OkDenAl

2022-11-07 06:55 UTC, merged

2022-11-07 15:58 UTC, Mazdaywik commented
У @uma-op появились коммиты в `main`! Ура!