Контракт API
bmstu-iu9/ptp2022-8-todo-list pull request #35
Opened 2022-07-14 18:23 UTC by stewkk

Closes #25

2022-07-15 14:42 UTC, geogreck commented
Добрый день, Александр! У вас не прошел линтер.
С уважением, Гречко Георгий

2022-07-16 11:53 UTC, stewkk commented
С актуальной версией документации из этого PR можно ознакомиться [тут](https://ptp.starovoytovai.ru/api/docs/).

2022-07-16 16:36 UTC, geogreck requested changes
1. Неверное описание структуры лейбл
2. Почему срок задачи называется dueDate, а дата создания created_on Было бы резонно использовать одинаковые стили названяи переменных.
![image](https://user-images.githubusercontent.com/74151984/179363796-1a4c92ab-2f85-42ef-ac49-2e17fcb4054c.png)
1. Код 418 возвращает другое сообщение.
![image](https://user-images.githubusercontent.com/74151984/179363892-c7ee9146-8ded-4106-8e15-be8beb23048c.png)

2022-07-17 14:01 UTC, geogreck approved these changes

2022-07-17 14:26 UTC, merged