Рабочий todo list
bmstu-iu9/ptp2022-8-todo-list pull request #36
Opened 2022-07-14 20:00 UTC by geogreck

Написана первая "полноценно" рабочая версия списка дел.
Реализовано:
- Быстрое добавление задач
- Добавление задач с доп параметрами(кроме файлов)
- Задачи можно удалять
- Задачи можно сохранять в локальное хранилище `saveAll()` в консоли браузера и выгружать из хранилища `getFromStorage()`
- Задачам можно присваивать лейблы
- Можно создавать свои лейблы
- Оно работает. Оно мне нравится.

2022-07-14 20:06 UTC, geogreck commented
Смотришь на линтер и думаешь, а надо ли оно тебе?

2022-07-17 07:21 UTC, Mazdaywik commented on frontend/html/todo.html
> +                </div> -->
А когда их можно будет раскомментировать?

2022-07-17 09:59 UTC, geogreck commented
Хотелось бы знать, чем в этой ситуации оправдан `force-push`

2022-07-17 10:27 UTC, Mazdaywik commented
Бо́льшая часть закомментированного кода удалена, меньшая (две строчки) — добавлена.

`force-push` оправдан тем, что пока ветка «личная», не влита в `main` и никто другой с ней не работает, можно написать более выразительную историю.

2022-07-26 12:40 UTC, geogreck commented
К **значительным изменениям** туду-листа относятся:
- Произведен частичный рефакторинг: код разбит по нескольким файлам, все файлы теперь в отдельной папке ../js/todo/
- Добавлена универсальная функция отправки запросов на сервер
- Все задачи и лейблы теперь хранятся на фейковом `json-server`, который хостится на [моем сервере](http://json.grechkogv.ru/tasks). Убедительная просьба не отправлять туда ***ненадлежащий*** контент.
- Отказ от использования локального хранилища, задачи и лейблы теперь хранятся в структуре `Map`.
- Отказ от использования `rgb` цветов в пользу `#hex-string`
- Реализован фильтр задач по статусу(`активные`,`завершенные`,`архивированные`)
- Удаленные задачи теперь удаляются навсегда и ото всюду.
- Что-то мог забыть...

2022-07-26 13:18 UTC, viacheslavek requested changes
Обширная и полезная работа, все хорошо, но 
 - нужно добавить ссылку на магазин shop.html в левом боковом меню

2022-07-26 13:18 UTC, viacheslavek commented on frontend/js/list/todolist.ts
> +    }
Отличная работа :3

2022-07-26 13:18 UTC, viacheslavek commented on frontend/js/request.ts
> +            const e = new Error('Пиво')
Не одобряю

2022-07-26 13:20 UTC, VyacheslavIsWorkingNow commented on frontend/html/todo.html
вот тут, на 67 строчке :)

2022-07-26 13:29 UTC, t1d333 commented on frontend/js/list/task.ts
> +    private shtirlitchHumoresque: string
Штирлиц долго смотрел в одну точку. Потом перевел взгляд
и посмотрел на другую.
"Двоеточие!" - догадался Штирлиц.

2022-07-26 14:15 UTC, VyacheslavIsWorkingNow approved these changes

2022-07-26 14:15 UTC, viacheslavek commented
Молодец :3

2022-07-26 14:18 UTC, merged