Добавил описание проекта 1 версии (улучшить описание стека технологий)
bmstu-iu9/ptp2022-8-todo-list pull request #5
Opened 2022-07-06 20:24 UTC by VyacheslavIsWorkingNow

Добавил начальную версию описания проекта. По ходу разработки будем корректировать и добавлять информацию.

2022-07-06 21:02 UTC, geogreck requested changes
Небольшие замечания по использованию разметки `markdown` и некорректное использование технической терминологии.
В целом хорошо написанный, красивый текст

2022-07-06 21:02 UTC, geogreck commented on README.md
> +**TODO-лист c дополнительной мотивацией, выполненной в игровой форме**
Предлагаю использовать заголовок второго уровня ##

2022-07-06 21:02 UTC, geogreck commented on README.md
> +Они характеризуются двумя группами — ****единовременные и накопительные****.
**** индентично **

2022-07-06 21:02 UTC, geogreck commented on README.md
> +Во фронтенде мы используем ***html + css + js*** (стандарт),
Для выделения технических терминов лучше оборачивать в обратные апострофы
```
**`html + css + js`**
```

Так же используемые технологии нужно будет указать точнее, но лучше позже, когда мы точно определимся с выбором.

2022-07-06 21:02 UTC, geogreck commented on README.md
> +а так же берем шаблоны для вёрстки c bootstrap.
```
`bootstrap`
```

2022-07-06 21:02 UTC, geogreck commented on README.md
> +В этом так же использовался фреймворк **Parcel**.
`Parcel` не фреймворк! Стыдно, Вячеслав!

2022-07-06 21:02 UTC, geogreck commented on README.md
> +Александр ***@stewkk*** Старовойтов — LEAD Backend
Ники можно превратить в гиперссылки на гитхабы участников для красоты.

2022-07-06 21:02 UTC, geogreck commented on README.md
> +Георгий ***@geogreck*** Гречко — LEAD frontend
Приятно.

2022-07-06 21:13 UTC, VyacheslavIsWorkingNow commented on README.md
> +Во фронтенде мы используем ***html + css + js*** (стандарт),
так и вправду красивее ;)

2022-07-06 21:16 UTC, VyacheslavIsWorkingNow commented on README.md
> +В этом так же использовался фреймворк **Parcel**.
Инструмент сборки нулевой конфигурации для web
Каюсь :(

2022-07-06 21:29 UTC, geogreck requested changes

2022-07-06 21:29 UTC, geogreck commented on README.md
> +##TODO-лист c дополнительной мотивацией, выполненной в игровой форме
Забыл пробел.

2022-07-06 21:30 UTC, viacheslavek commented on README.md
> +##TODO-лист c дополнительной мотивацией, выполненной в игровой форме
-_-

2022-07-06 21:46 UTC, geogreck approved these changes
Поздравляю!

2022-07-06 21:47 UTC, merged

2022-07-07 05:38 UTC, Mazdaywik commented on README.md
> +Александр ***@stewkk*** Старовойтов — LEAD Backend
Не можно, а нужно. К концу практики я у всех буду требовать, чтобы в `README.md` были списки команд с кликабельными ссылками на профили.