Реализация деплоя фронтенда, создание SPA
bmstu-iu9/ptp2022-8-todo-list pull request #62
Opened 2022-07-29 21:58 UTC by geogreck

closes #58

2022-07-29 22:06 UTC, geogreck commented
Произошел отвал `HEAD`.

2022-08-05 14:58 UTC, geogreck commented
# **TO-DO**

- [ ] Пофиксить ЛИНТЕР
- [ ] Убедиться, что деплоймент `dev` версии не пострадал, работоспобность `Makefile` полностью сохранена
- [ ] Улучшить Handler в `static` сервере
- [ ] Произвести рефакторинг деплоймент скриптов
- [ ] Скрипты роутера портировать на `TS`(?)

2022-08-30 12:38 UTC, stewkk requested changes
> Как хорошо, что я не фронтендер!

P.S. Поправь варнинги линтера =)

2022-08-30 12:38 UTC, stewkk commented on Makefile
Отдельно фронт есть в режиме дев и прод, а все контейнеры только в дев. Мб, стоит добавить прод для всех контейнеров:
```suggestion

.PHONY: prod
prod:
	@docker compose up --build
	
```

2022-08-30 12:38 UTC, stewkk commented on Makefile
И, кстати, возможно стоит сделать `prod` режимом по умолчанию (при запуске с помощью `make`), т.к. сейчас `docker compose up` поднимает прод версию.

2022-08-30 12:38 UTC, stewkk commented on frontend/deploy/server.js
> +                    code,
Нужны константы для цветов

2022-08-30 12:38 UTC, stewkk commented on frontend/deploy/index.js
> +    throw new error()
Кринжанул =)

2022-08-30 12:38 UTC, stewkk commented on frontend/guide.md
> +        } catch (error) {}
😂

2022-08-30 12:38 UTC, stewkk commented on frontend/html/spa.html
> +            </html>
```suggestion
            </html>

```

2022-08-30 12:38 UTC, stewkk commented on frontend/html/spa.html
> +            </html>
И немного поехало форматирование =)

2022-08-30 12:38 UTC, stewkk commented on frontend/js/inventory/inventory.ts
> +        for (let i = 0; i < data.length; i++) {
Не канон!

2022-08-30 12:38 UTC, stewkk commented on frontend/js/inventory/inventory.ts
> +            //userImg!.setAttribute('src', `https://wg.grechkogv.ru/assets/${item.imageSrc}`)
Страшно

2022-08-30 12:38 UTC, stewkk commented on frontend/js/list/todolist.ts
> +            tasks.set(buf.id, newTask)
Печальная инициализация :/

2022-08-30 12:38 UTC, stewkk commented on frontend/js/spa/route.ts
> +    private fn: Function
Плохое название. Непонятно, что делает эта функция, и почему `evalFn` вызывает ее таким странным образом.

2022-08-30 12:38 UTC, stewkk commented on frontend/js/spa/route.ts
> +        }, 100)
Хочется плакать

2022-08-30 12:56 UTC, geogreck commented on frontend/js/spa/route.ts
> +        }, 100)
Мне тоже

2022-08-30 13:24 UTC, geogreck commented on frontend/html/spa.html
> +            </html>
Не немного.

2022-08-30 17:53 UTC, geogreck commented
Забыл добавить, что у страниц теперь наконец-то есть title!

2022-08-31 08:36 UTC, stewkk approved these changes

2022-08-31 08:41 UTC, merged