Изменения меню
bmstu-iu9/ptp2022-8-todo-list pull request #63
Opened 2022-07-29 23:52 UTC by Tanya-g99

closes #47

2022-08-01 12:56 UTC, VyacheslavIsWorkingNow requested changes
Я ещё пока работаю в этой ветке (делаю подгрузку магазина с json файла), так что пока рано ее закрывать)

2022-08-01 15:19 UTC, geogreck commented
Каков замысел пушить такие файлы?
![Screenshot_2022-08-01-18-19-10-82_21da60175e70af211acc4f26191b7a77](https://user-images.githubusercontent.com/74151984/182182929-9fb9a0a7-8b55-4da1-9760-f4156aff03b6.jpg)

2022-08-01 15:20 UTC, geogreck commented
Аналогично
![Uploading Screenshot_2022-08-01-18-20-12-91_21da60175e70af211acc4f26191b7a77.jpg…]()

2022-08-01 15:20 UTC, geogreck commented
Зачем делать копию уже существующего файла
![Screenshot_2022-08-01-18-20-03-57_21da60175e70af211acc4f26191b7a77](https://user-images.githubusercontent.com/74151984/182183209-a64ffc86-c94f-4978-a42d-a90bdede7c62.jpg)


Позже добавлю поддержку json
(Пока разбирался с тем, как работает вставка в html файл поля из объектов js)

2022-08-01 15:21 UTC, geogreck commented
Аналогично
![Screenshot_2022-08-01-18-20-12-91_21da60175e70af211acc4f26191b7a77](https://user-images.githubusercontent.com/74151984/182183361-1f341667-bee1-4fb0-ab9b-29cf1249e5ed.jpg)

2022-08-01 16:25 UTC, VyacheslavIsWorkingNow commented
В последующих коммитах удалю пустые файлы)
Сначала я задумал одну архитектуру, но потом решил обойтись единым js файлом.

2022-08-01 16:46 UTC, geogreck commented
А смысл пушить настолько кривую, не рабочую и отвратительно оформленную версию

2022-08-02 16:43 UTC, VyacheslavIsWorkingNow commented
Уже менее кривая, более рабочая и вроде бы средне оформленная версия 😅

2022-08-03 05:18 UTC, geogreck commented
Стыдно!
![Screenshot_2022-08-03-08-18-36-91_21da60175e70af211acc4f26191b7a77](https://user-images.githubusercontent.com/74151984/182529771-b9f1f32b-fcf6-4f9f-9ca6-efcd887d1777.jpg)

2022-08-05 14:16 UTC, VyacheslavIsWorkingNow commented
Позже добавлю построение модальных окон, используя dom дерево

2022-08-07 16:52 UTC, VyacheslavIsWorkingNow commented
Нужно будет поправить границы карточек (слева и справа выходят за основную страницу)

2022-08-07 17:11 UTC, geogreck commented on frontend/js/componentsShop/dom_modal.ts
> +    id: number;
Каков смысл существования этого файла, если он содержит уже только написанный Таней код ? Я бы сказал, 
"Обнаружены ОЧЕНЬ похожие решения"

2022-08-07 17:13 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +    else if (rarity === 'legendary') return "#F06292";
Эта функция копирует функцию, которая была скопирована у Татьяны в другом файле

2022-08-07 17:19 UTC, geogreck commented on frontend/js/componentsShop/dom_modal.ts
> +const modalInventory = new bootstrap.Modal(<HTMLFormElement>document.getElementById('shopModal'));
Код настолько внимательно копировался у Татьяны, что не изменено даже название модалки :)

2022-08-07 17:20 UTC, geogreck commented
Не помешало бы убрать код, который уже добавлен Татьяной при создании инвентаря, чтобы не было дублирования + убрать все `ts-ignore`

2022-08-07 17:21 UTC, geogreck commented on frontend/js/componentsShop/dom_modal.ts
> +const modalInventory = new bootstrap.Modal(<HTMLFormElement>document.getElementById('shopModal'));
Кстати в продакшене это будет приводить к ошибке выполнения :)

2022-08-07 19:16 UTC, VyacheslavIsWorkingNow commented
По твоим комментариям сверху может сложиться впечатление, что я втихую присвоил код Татьяны. Но ведь мы с тобой вместе обсуждали то, что проще и быстрее будет  использовать уже имеющуюся технологию, и для этого Таня помогала мне, добавив комментарии и отвечав мне на мои вопросы в сообщениях. Функцию получения цвета я пока оставил здесь, так как она находится в другой ветке и пока мне недоступна, как и тип item, позже, после слияния, мы оставим только одну. Остальные функции я подстраивал под то, что мне нужно на этой странице. Замечания принял к сведению и исправлю их. 
В некоторых ваших комментариях я хотел бы лучше видеть анекдоты, а не попытку задеть меня(

2022-08-07 19:37 UTC, geogreck commented
То что код бывает реализован в другой ветке, а в твоей нет, это обычное дело. Есть два простых пути решения:
1) (так себе) слить ветку с кодом в свою ветку
2) (хороший) пнуть авторов другой ветки, чтобы ее слили в Мейн и уже слить мейн в свою ветку
А пушить такой код ещё раз в свою ветку никак нельзя, так как это банально приведет к неработоспособности проекта в мейне, что можно не отловить заранее, особенно учитывая то, что у тебя весь код в `@ts-ignore`.

2022-08-09 17:18 UTC, VyacheslavIsWorkingNow commented
Основная работа сделана, буду исправлять замечания (предписания) Георгия

2022-08-09 17:21 UTC, geogreck reviewed
К правкам Татьяны и картинкам вопросов не имею

2022-08-09 17:47 UTC, geogreck requested changes

2022-08-09 17:47 UTC, geogreck commented on frontend/html/shop.html
> +    <script defer src="../js/inventory/inventory.ts"></script>
Зачем подключается этот скрипт?

2022-08-09 17:47 UTC, geogreck commented on frontend/html/shop.html
> +        <br>
Зачем `<br>`?

2022-08-09 17:47 UTC, geogreck commented on frontend/html/shop.html
> +            Мифическая:  linear-gradient(#40E0D0, #FF8C00, #FF0080)
Ненужный комментарий

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/dom_modal.ts
> +const itemsShop = new Map<number, Item>();
Файл неплохо было бы прогнать через форматтер, слишком уж много лишних отступов

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/dom_modal.ts
> +    const strId = findID(target, regexp);
Снова лишний отступ

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/dom_modal.ts
> +            </button>
Кнопка в модалке не по центру

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/dom_modal.ts
> +        // делать по центру одинаково
По вертикали модальное окно не по центру

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +        CATALOG_SHOP.forEach(({id, name, description, imageSrc, category, rarity, state}) => {
Почему не используется просто элемент типа `item`

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +class Products {
Файл бы тоже прогнать через форматтер

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +})
Почему баланс хранится только в коде страницы?

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +        const itemBuy: Item = itemsCostShop.get(cost)!;
Довольно странно каждый раз производить такие длинные вычисления, вместо того, чтобы просто взять цену из таблицы предметов

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +        itemsCostShop.set(item.price, item);
Замысел этого кода к сожалению понять не удалось. Зачем делать ещё одно хранилище предметов, если есть itemsShop?

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +        let balanceBuy: number = parseInt(balanceShopForBuyAndString.replace(/\D+/g,""));
Довольно странно каждый раз производить такие длинные вычисления, вместо того, чтобы просто взять баланс из переменной

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +        console.log(balanceBuy);
Не убранный console.log

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +            console.log(itemBuy);
Снова они же

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +    })
Для этого так же можно  использовать функцию `sendRequest`

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +        else if (balanceBuy >= cost && (itemBuy.state == 'inventoried' || itemBuy.state == 'equipped')) {
Очень странно написаны `if`-ы. Во-первых если верить надежности кода, у купленного предмета изначально написано, что его купить нельзя, а значит смысл от этих всех проверок? Во-вторых если вдруг нет уверенности в работоспособности своего кода и такая проверка нужна, можно сначала сделать проверку `balanceBuy >= cost` и уже внутри сделать проверку, не куплен ли предмет

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +        let numberBlock = 0;
Зачем нужна переменная `numberBlock`

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +                        <!- модальное окно --->
Не убранный комментарий

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +                category === 'skin' && numberBlock === 3) {
ОЧЕНЬ странный `if`. Если уж выбран странный алгоритм запихивания всего каталога в одну переменную, то проверку на новый логический блок можно делать по смене типа предмета

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +                        <br>
Зачем `<br>`?

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +        `;
Что делает этот код?

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +        `;
вопрос риторический - ничего

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +        ROOT_PRODUCTS.innerHTML = html;
Весь код страдает от разного стиля названия переменных, то используется `camelCase`, то `CONSTATN_CASE`, причем не только для констант

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +let CATALOG_SHOP = [];
Как тут

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/products.ts
> +                                Куплено</button>
А зачем это создавать как активную кнопку, если предмет уже куплен и ничего с ним сделать нельзя?

2022-08-09 17:47 UTC, geogreck commented on frontend/js/componentsShop/dom_modal.ts
> +});
Нет перехода на новую строку. Чинится запуском форматтера.

2022-08-09 17:50 UTC, VyacheslavIsWorkingNow commented on frontend/html/shop.html
> +    <script defer src="../js/inventory/inventory.ts"></script>
Для функции определения цвета карточки и доступа к типу Item (последние две)

2022-08-09 17:51 UTC, viacheslavek commented on frontend/html/shop.html
> +    <script defer src="../js/inventory/inventory.ts"></script>
Или это можно сделать как-то лучше?)

2022-08-09 17:51 UTC, VyacheslavIsWorkingNow commented on frontend/js/componentsShop/dom_modal.ts
> +const itemsShop = new Map<number, Item>();
Окс

2022-08-09 17:54 UTC, geogreck commented
Забыл указать, что открытие любого модального окна приводит к ошибке:
```js
Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at Hi._isAnimated (modal.js:313:26)
    at Hi._initializeBackDrop (modal.js:195:24)
    at new Hi (modal.js:83:27)
    at Function.getOrCreateInstance (base-component.js:55:41)
    at HTMLButtonElement.<anonymous> (modal.js:421:22)
    at HTMLDocument.n (event-handler.js:119:21)
```

2022-08-09 17:56 UTC, geogreck commented
И почему при покупке предмета об этом никак не пишется в модальном окне, нужно обновлять страницу? 
Это не так уж и сложно

2022-08-09 17:58 UTC, geogreck commented on frontend/html/shop.html
> +    <script defer src="../js/inventory/inventory.ts"></script>
Ничего из вышеперечисленного в файле `inventory.ts` нет

2022-08-09 18:04 UTC, VyacheslavIsWorkingNow commented on frontend/html/shop.html
> +    <script defer src="../js/inventory/inventory.ts"></script>
Упс

2022-08-09 18:06 UTC, VyacheslavIsWorkingNow commented
Да, это нужно добавить

2022-08-10 09:23 UTC, VyacheslavIsWorkingNow commented on frontend/html/shop.html
> +        <br>
![Снимок 10 08 2022 в 12 21](https://user-images.githubusercontent.com/89520622/183865503-ed8e1b61-edc8-4f9c-8dba-6a5ba45ee212.jpg)
с <br> проще попасть на кнопку купить, да и просто глазу приятнее
вот без
![Снимок 10 08 2022 в 12 21](https://user-images.githubusercontent.com/89520622/183865652-66d9bd76-ede5-4922-a5ee-3fba661203a3.jpg)
:

2022-08-10 09:24 UTC, VyacheslavIsWorkingNow commented on frontend/html/shop.html
> +        <br>
На белом фоне не видно...... Ну тогда стоит поверить на слово (или проверить :3)

2022-08-10 09:31 UTC, geogreck commented on frontend/html/shop.html
> +        <br>
Для этого используют свойства `margin` или `padding`

2022-08-10 09:44 UTC, VyacheslavIsWorkingNow commented on frontend/js/componentsShop/products.ts
> +                                Куплено</button>
Изменил систему кнопок
см - первый кормит после ревью

2022-08-10 09:46 UTC, VyacheslavIsWorkingNow commented on frontend/js/componentsShop/dom_modal.ts
> +const itemsShop = new Map<number, Item>();
Прогнал через встроенный в ide, некоторые добавил сам для читабельности (разделения на блоки)

2022-08-10 09:59 UTC, VyacheslavIsWorkingNow commented on frontend/html/shop.html
> +        <br>
Изучил - согласен

2022-08-12 15:03 UTC, VyacheslavIsWorkingNow submitted a review, later dismissed

2022-08-13 11:10 UTC, VyacheslavIsWorkingNow commented
Вроде бы все правки внесены, жду вашего решения, @geogreck :)

2022-08-23 20:22 UTC, geogreck commented on frontend/js/componentsShop/dom_modal.ts
> +        windowForm.style.width = `calc(${buf.right - buf.x}*1.2px + 3vw + 3.8rem)`;
Бесполезный код, не делающий ничего

2022-08-29 09:21 UTC, geogreck commented
Мюллер решил устроить проверку сотрудников. Вызывает в кабинет Шелленберга:
— Шелленберг, назовите какое-нибудь число. Любое.
— Ну, предположим, 32.
— А почему не 23?
— потому что 32!
Мюллер пишет в личном деле: «Характер нордический, стойкий».
Вызывает Кальтенбруннера.
— Кальтенбруннер, назовите какое-нибудь число.
— 67.
— А почему не 76?
— Ну, можно и 76.
Мюллер пишет в личном деле: «Характер близкий к нордическому». Вызывает следующего.
— Назовите любое число.
— VyacheslavIsWorkingNow reopened this 17 hours ago!
— А почему не... А-а, это вы, @VyacheslavIsWorkingNow !

2022-08-29 15:33 UTC, geogreck approved these changes

2022-08-29 15:34 UTC, merged