Добавление реализации операций с вещами
bmstu-iu9/ptp2022-8-todo-list pull request #65
Opened 2022-07-31 09:14 UTC by OkDenAl

Первая версия операций с вещами (думаю, в дальнейшем её предстоит править, но на данный момент разработки проекта, я считаю, она полная)

2022-07-31 10:00 UTC, uma-op commented on backend/internal/items/api.go
> +	mux.GET("/users/:userId/items", accesslog.Log(res.handleGetAll, logger))
Зачем передавать id юзера, если мы в любом случае получаем все имеющиеся вещи?

2022-07-31 10:36 UTC, OkDenAl commented on backend/internal/items/api.go
> +	mux.GET("/users/:userId/items", accesslog.Log(res.handleGetAll, logger))
Пока что это никак не мешает и действительно не имеет смысла, разве что в том, что всё это добро будет выводиться на странице конкретного пользователя, в дальнейшем есть идея добавить некоторые фильтры для метода GetAll под конкретного юзера, а для этого так или иначе надо передавать id юзера

2022-07-31 10:39 UTC, uma-op commented on backend/internal/entity/item.go
> +	IsInInventory bool `json:"is_in_inventory"`
По моему поле наличия вещи в инвентаре не нужно, так как особо и не используется. Клиент запрашивает либо все вещи из базы ( в этом случае поле "IsInInventory" выглядит странно ), либо вещь какого то пользователя ( тогда наличие вещи в инвенторе определяется кодом возврата ). Это поле имело бы смысл, если запрашивать вещи от имени конкретного пользователя ( вероятно такой смысл изначально закладывался в эндпоинт получения всех вещей ).

2022-07-31 10:44 UTC, uma-op commented on backend/internal/items/service_test.go
> +	/*newItem.ItemName = ""
Закомментированный код лучше не оставлять

2022-07-31 11:01 UTC, uma-op approved these changes, later dismissed
Помимо тех замечаний, других нет.

2022-07-31 11:08 UTC, OkDenAl commented on backend/internal/items/service_test.go
> +	/*newItem.ItemName = ""
Упс, забыл 👉👈

2022-07-31 15:35 UTC, stewkk requested changes
Мегахорош =)

2022-07-31 15:35 UTC, stewkk commented on backend/internal/db/db.go
> +DROP TABLE IF EXISTS users CASCADE ;
```suggestion
DROP TABLE IF EXISTS users CASCADE;
```

2022-07-31 15:35 UTC, stewkk commented on backend/internal/db/db.go
> +DROP TABLE IF EXISTS items CASCADE ;
```suggestion
DROP TABLE IF EXISTS items CASCADE;
```

2022-07-31 15:35 UTC, stewkk commented on backend/internal/db/db.go
>  INSERT INTO users(email, nickname, password)
```suggestion
INSERT INTO users (email, nickname, password)
```

2022-07-31 15:35 UTC, stewkk commented on backend/internal/db/db.go
>  VALUES('test@example.com', 'test', 'Test123Test');
```suggestion
VALUES ('test@example.com', 'test', 'Test123Test');
```

2022-07-31 15:35 UTC, stewkk commented on backend/internal/db/db.go
> +VALUES('test2@example.com', 'test2', 'Test123Test');
```suggestion
INSERT INTO users (email, nickname, password)
VALUES ('test2@example.com', 'test2', 'Test123Test');
```

2022-07-31 15:35 UTC, stewkk commented on backend/internal/db/db.go
> + VALUES ('testItem2','test2.png','test2',62,'test2','test2');
```suggestion
INSERT INTO items (item_name, image_src, description, price, category, rarity) 
VALUES ('testItem1', 'test.png', 'test1', 65, 'test1', 'test1');
INSERT INTO items (item_name, image_src, description, price, category, rarity) 
VALUES ('testItem2', 'test2.png', 'test2', 62, 'test2', 'test2');
```

2022-07-31 15:35 UTC, stewkk commented on backend/internal/db/db.go
> +    is_equipped bit,
Тут, наверное, лучше использовать [`boolean`](https://www.postgresql.org/docs/current/datatype-boolean.html).

2022-07-31 15:35 UTC, stewkk commented on backend/internal/db/db.go
> +INSERT INTO users_items (user_id, item_id,is_equipped) VALUES (1,2,'1');
```suggestion
INSERT INTO users_items (user_id, item_id, is_equipped) VALUES (1, 1, '0');
INSERT INTO users_items (user_id, item_id, is_equipped) VALUES (2, 1, '0');
INSERT INTO users_items (user_id, item_id, is_equipped) VALUES (1, 2, '1');
```

2022-07-31 15:35 UTC, stewkk commented on backend/internal/entity/item.go
> +	IsInInventory bool `json:"is_in_inventory"`
> По моему поле наличия вещи в инвентаре не нужно, так как особо и не используется. Клиент запрашивает либо все вещи из базы ( в этом случае поле "IsInInventory" выглядит странно ), либо вещь какого то пользователя ( тогда наличие вещи в инвенторе определяется кодом возврата ). Это поле имело бы смысл, если запрашивать вещи от имени конкретного пользователя ( вероятно такой смысл изначально закладывался в эндпоинт получения всех вещей ).

Я предполагал использовать коллекцию `/users/{id}/items` для всех действий с предметами:
- т.к. у нас есть магазин и инвентарь, а список предметов для каждого пользоватя одинаков, мы не делаем отдельный эндпоинт для преметов, все предметы отдаем по `GET /users/{id}/items`. Тогда мы используем простые состояния предмета: "в магазине", "в инвентаре", "экипирован" (или что-то подобное). Это позволяет получать все предметы и их состояния одним запросом. А если, например, необходимы предметы только из инвентаря, это можно реализовать с помощью фильтра;
- `PATCH /users/{userId}/items/{itemId}` позволяет перемещать предметы магазин->инвентарь, инвентарь->экипирован и т.д. одним запросом с изменением поля состояния.

2022-07-31 15:35 UTC, stewkk commented on backend/internal/entity/item.go
> +//Struct Item describing one item
```suggestion
// A Item represents single in-game item
```

2022-07-31 15:35 UTC, stewkk commented on backend/internal/db/db.go
> +    rarity varchar (30) NOT NULL
Тут прикольно было бы использовать [`enum`](https://www.postgresql.org/docs/current/datatype-enum.html) (но необязательно).

2022-07-31 15:35 UTC, stewkk commented on backend/internal/entity/item.go
> +	IsInInventory bool `json:"is_in_inventory"`
Можно пока оставить как есть, но после закрытия #57, думаю придется заменить на `enum`.

2022-07-31 15:35 UTC, stewkk commented on backend/internal/items/api.go
> +	mux.PATCH("/users/:userId/items/:itemId", accesslog.Log(res.handlePatch, logger))
Хорошая мысль - делать хендлеры неэкспортируемыми. Создал issue #66.

2022-07-31 15:35 UTC, stewkk commented on backend/internal/items/repository.go
> +func (repo repository) checkUsersItem(userId, itemId int) (status bool, err error) {
Название `checkUsersItem` не очень.

2022-07-31 15:35 UTC, stewkk commented on backend/internal/items/repository.go
> +		"AND users_items.item_id = $2 AND users_items.user_id = $3", itemId, itemId, userId)
```suggestion
	row, err := repo.db.Query("SELECT items.id, item_name, image_src,"+
		" description, price, category, rarity, users_items.is_equipped FROM items INNER JOIN users_items ON items.id = $1"+
		"AND users_items.item_id = $2 AND users_items.user_id = $3", itemId, itemId, userId)
```

2022-07-31 15:35 UTC, stewkk commented on backend/internal/items/repository.go
> +
Потерял docstring'и к экспортируемым функциям =)

2022-07-31 15:35 UTC, stewkk commented on backend/internal/items/service.go
> +
Тут тоже потерял docstring'и =)

2022-07-31 15:53 UTC, OkDenAl commented on backend/internal/items/api.go
> +	mux.PATCH("/users/:userId/items/:itemId", accesslog.Log(res.handlePatch, logger))
Хи )

2022-07-31 15:54 UTC, OkDenAl commented on backend/internal/items/repository.go
> +func (repo repository) checkUsersItem(userId, itemId int) (status bool, err error) {
А как лучше назвать ? isItemBelongsToUser ?

2022-07-31 15:54 UTC, OkDenAl commented on backend/internal/items/repository.go
> +
Допилю

2022-07-31 15:56 UTC, OkDenAl commented on backend/internal/entity/item.go
> +	IsInInventory bool `json:"is_in_inventory"`
типа isInventory сделать enum?

2022-07-31 15:57 UTC, OkDenAl commented on backend/internal/db/db.go
> +    is_equipped bit,
да, наверное, не знал про это) спасибо

2022-07-31 15:58 UTC, OkDenAl commented on backend/internal/db/db.go
> +    rarity varchar (30) NOT NULL
прикольная тема, добавлю

2022-07-31 16:01 UTC, geogreck commented
Ребят, вы бы на улицу вышли

2022-07-31 16:01 UTC, stewkk commented on backend/internal/entity/item.go
> +	IsInInventory bool `json:"is_in_inventory"`
> типа isInventory сделать enum?

Вместо полей `IsEquipped`, `IsInInventory` сделать `enum` с состояниями (пример: `type Rarity = 'common' | 'rare' | 'epic' | 'legendary'`)

2022-07-31 16:14 UTC, stewkk commented on backend/internal/items/repository.go
> +func (repo repository) checkUsersItem(userId, itemId int) (status bool, err error) {
> А как лучше назвать ? isItemBelongsToUser ?

Если ты поменяешь на `enum`, то можно `getItemState`. А если оставлять так, то можно `isItemBelongsToUser`.

2022-07-31 20:03 UTC, uma-op commented on backend/internal/entity/item.go
> +	IsInInventory bool `json:"is_in_inventory"`
> > По моему поле наличия вещи в инвентаре не нужно, так как особо и не используется. Клиент запрашивает либо все вещи из базы ( в этом случае поле "IsInInventory" выглядит странно ), либо вещь какого то пользователя ( тогда наличие вещи в инвенторе определяется кодом возврата ). Это поле имело бы смысл, если запрашивать вещи от имени конкретного пользователя ( вероятно такой смысл изначально закладывался в эндпоинт получения всех вещей ).
> 
> Я предполагал использовать коллекцию `/users/{id}/items` для всех действий с предметами:
> 
> * т.к. у нас есть магазин и инвентарь, а список предметов для каждого пользоватя одинаков, мы не делаем отдельный эндпоинт для преметов, все предметы отдаем по `GET /users/{id}/items`. Тогда мы используем простые состояния предмета: "в магазине", "в инвентаре", "экипирован" (или что-то подобное). Это позволяет получать все предметы и их состояния одним запросом. А если, например, необходимы предметы только из инвентаря, это можно реализовать с помощью фильтра;
> * `PATCH /users/{userId}/items/{itemId}` позволяет перемещать предметы магазин->инвентарь, инвентарь->экипирован и т.д. одним запросом с изменением поля состояния.

В таком случае, функция GetAll из repository.go уже могла бы учитывать user_id и помечать вещи как находящиеся в инвентаре. Ну или, конечно, можно это оставить до того как начнём делать фильтры.

2022-08-01 08:01 UTC, stewkk commented on backend/internal/entity/item.go
> +	IsInInventory bool `json:"is_in_inventory"`
> В таком случае, функция GetAll из repository.go уже могла бы учитывать user_id и помечать вещи как находящиеся в инвентаре. Ну или, конечно, можно это оставить до того как начнём делать фильтры.

Я думал, она так и делает =)

2022-08-01 16:33 UTC, VyacheslavIsWorkingNow commented
Вот это я понимаю обсуждения)

2022-08-01 16:45 UTC, Mazdaywik commented
> Вот это я понимаю обсуждения)

Я рад, что этому вас научил!

2022-08-02 19:59 UTC, uma-op commented on backend/internal/db/db.go
> +INSERT INTO users (email, nickname, password)
Кортежи значений можно перечислять сразу через запятую в одном запросе

2022-08-02 19:59 UTC, uma-op commented on backend/internal/db/db.go
> +INSERT INTO items (name, image_src, description, price, item_category, item_rarity)
аналогично

2022-08-02 20:00 UTC, uma-op commented on backend/internal/db/db.go
> +INSERT INTO inventory (user_id, item_id,item_state) VALUES (1, 2, 'equipped');
и тут

2022-08-02 20:20 UTC, uma-op commented on backend/internal/items/repository.go
> +	return sqlQueryRarity, sqlQueryCategory
т.к. в сигнатуре написал имена возвращаемых переменных то в ретюрне их по идее можно не указывать
просто return будет достаточно

2022-08-02 20:31 UTC, uma-op commented on backend/internal/items/repository.go
> +	return sqlQueryRarity, sqlQueryCategory
и в принципе можно ведь одну строку возвращать

2022-08-02 20:37 UTC, uma-op commented on backend/internal/items/repository.go
> +func (repo repository) IsItemInInventory(userId, itemId int) (status entity.State, err error) {
тут тоже прикол с именами в сигнатуре, но тут еще и сторонние возвраты

2022-08-02 20:40 UTC, uma-op commented on backend/internal/items/repository.go
> +func (repo repository) GetOne(userId, itemId int) (entity.Item, error) {
а тут имен в сигнатуре нет)

2022-08-02 20:42 UTC, uma-op commented on backend/internal/entity/item.go
> +type State string
может лучше int?

2022-08-02 20:46 UTC, uma-op commented on backend/internal/items/service.go
> +func NewFilter(r *http.Request) entity.Filter {
у тебя же есть httprouter.Params

2022-08-02 21:13 UTC, uma-op requested changes
Все прокомментировал. Перечисления предлягаю сделать через побитовую логику ( 1 << iota )

2022-08-03 05:08 UTC, OkDenAl commented on backend/internal/items/repository.go
> +func (repo repository) IsItemInInventory(userId, itemId int) (status entity.State, err error) {
Да, чёт наговнокодил...

2022-08-03 05:10 UTC, OkDenAl commented on backend/internal/entity/item.go
> +type State string
Прикол в том, что если делать int, то тогда в функции где идёт считывание проверки состояния из БД придётся вместо обычного присваивания считанного статуса делать switch case

2022-08-03 05:15 UTC, geogreck commented on backend/internal/entity/item.go
> +type State string
Так может сделать enum?

2022-08-04 06:10 UTC, OkDenAl commented on backend/internal/entity/item.go
> +type State string
> Так может сделать enum?

В го нет enum как-такового, что предлагает Сеня это есть имитация enum, но как я сказал, мне это кажется не удобным, ведь есть случай GetOne, где идёт считывание состояния из БД, а в БД состояние это enum со строковыми параметрами

2022-08-05 13:59 UTC, OkDenAl commented on backend/internal/items/service.go
> +func NewFilter(r *http.Request) entity.Filter {
Через них не получилось, он почему-то не отлавливает

2022-09-05 10:28 UTC, stewkk requested changes
Надо было все-таки сначала писать контракт, а потом реализацию предметов =)

2022-09-05 10:28 UTC, stewkk commented on backend/internal/entity/item.go
> +	ItemName    string `json:"item_name"`
А зачем называть поля Item... ?

2022-09-05 10:28 UTC, stewkk commented on backend/internal/entity/item.go
> +	ItemState State `json:"item_state"`
И тут

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/api.go
> +func RegisterHandlers(mux *httprouter.Router, service Service, logger log.Logger) {
Потерял docstring

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/service.go
> +func NewFilter(r *http.Request) entity.Filter {
> у тебя же есть httprouter.Params

httprouter работает только с параметрами пути (path parameters)

2022-09-05 10:28 UTC, stewkk commented on backend/internal/entity/item.go
> +)
Тут нужны docstring'и

2022-09-05 10:28 UTC, stewkk commented on backend/internal/entity/item.go
> +	Rarity      string `json:"rarity"`
поле 'Rarity' так же должно быть `enum`

2022-09-05 10:28 UTC, stewkk commented on backend/internal/entity/item.go
> +}
В пакете `entity` объявляются доменные объекты. Тут ты объявил тип `entity.Filter`. Из этого вытекают следующие проблемы:
1. фильтр предметов не является доменным объектом;
2. тип `entity.Filter` не несет в себе информацию о том, что это фильтр для предметов.

Логичнее было бы объявить `type Filter struct` в `items/repository.go`, т.к. этот тип используется именно репозиторием. Задача уровня api - распарсить запрос и преобразовать в необходимый формат для передачи в бизнес-логику (`newFilter()`). Бизнес-логика, в свою очередь, может валидировать само содержимое этих параметров. Далее, эти данные получает репозиторий и выполняет SQL-запросы. Получается, что тип `items.Filter` не не относится к доменым объектам (он не хранится в БД), а является параметром для репозитория - какие данные запрашиваются из БД.

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/service.go
> +// NewFilter creates a new filter.
Недостаточно информации.

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/service.go
> +func NewFilter(r *http.Request) entity.Filter {
Почему `NewFilter` объявляется в `service.go`? По сути, это работа с параметрами запроса. Это никак не относится к уровню бизнес-логики. Это должно быть объявлено на уровне апи.

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/api.go
> +	w.WriteHeader(http.StatusOK)
В силу особенностей пакета `net/http`, `w.WriteHeader` нужно вызывать до `Encode()`.

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/api.go
> +	w.WriteHeader(http.StatusOK)
Аналогично

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/api.go
> +	w.WriteHeader(http.StatusOK)
И тут

2022-09-05 10:28 UTC, stewkk commented on backend/internal/entity/item.go
> +)
`entity.State`:
1. не несет информации о том, что этот тип представлет состояние ПРЕДМЕТА;
2. если в будущем будут создаваться новые состояния для других объектов, это будет error-prone, т.к. состояние `Equipped` можно будет присвоить, например, персонажу, хотя такое состояние для него не задумывалось.

Поэтому, нужно переименовать в `entity.ItemState`.

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/service.go
> +type UpdateItemStateRequest struct {
Спорное название

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/service.go
> +		CategoryFilter: r.URL.Query().Get("categoryfilter"),
Неидеоматичные названия для параметров. Обычно используют просто название поля, по которому происходит филтрация (пример: `r.URL.Query().Get("rarity")`.

2022-09-05 10:28 UTC, stewkk commented on backend/internal/entity/item.go
> +}
Также, функционал этих фильтров слишком узок. Например, клиент не может получить предметы с состоянием `equipped` и `inventoried` одновременно.

Нужно реализовать фильтры через перечисления: `state=equipped,inventoried` - вернет предметы с состоянием `equipped` и `inventoried`.

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/service.go
> +// GetOne returns item with specified id owned by user with specified id.
Зачем такое поведение?

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/service.go
> +func (s service) Modify(userId, itemId int, input *UpdateItemStateRequest) (entity.Item, error) {
Называешь функцию `Modify`, а ее параметр - `UpdateItemStateRequest`

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/service.go
> +	status, err := s.repo.IsItemInInventory(userId, itemId)
Зачем?

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/service.go
> +	}
Такого не может быть

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/service.go
> +	err = s.repo.Update(userId, &entityItem)
Вообще не понял, что это =)

Тут какая-то лишняя логика

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/repository.go
> +func createSqlQuery(filters entity.Filter) string {
Плохое название

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/repository.go
> +		sqlQueryRarity = fmt.Sprintf("WHERE item_rarity = '%s'", filters.RarityFilter)
Нельзя использовать `fmt.Sprintf` при формировании SQL-запросов, это [небезопасно](https://go.dev/doc/database/sql-injection).

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/repository.go
> +	items := make([]entity.Item, 0)
Можно упростить

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/repository.go
> +	"github.com/bmstu-iu9/ptp2022-8-todo-list/backend/internal/log"
А это вообще работает без иморта:
```go
	_ "github.com/lib/pq"

```
?

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/repository.go
> +func (repo repository) Create(userId, itemId int, state entity.State) error {
Мб лучше изначально хранить все предметы в таблице пользователя. Тогда добавление предмета в инвентарь будет той же операцией Update, что сильно упростит логику репозитория. Ведь идиоматически репозиторий просто сохраняет данные в хранилище, а сейчас на нем лежит лишняя логика.

2022-09-05 10:28 UTC, stewkk commented on backend/internal/items/repository.go
> +		if countOfFilters == 1 {
Как-то сложно написано

2022-09-05 10:42 UTC, geogreck commented on backend/internal/items/repository.go
> +		sqlQueryRarity = fmt.Sprintf("WHERE item_rarity = '%s'", filters.RarityFilter)
Безопасно. Как глава фронтенда, я считаю эссенциальным оставить возможность дропать таблицу с помощью запроса с клиента

2022-09-06 15:27 UTC, OkDenAl commented on backend/internal/items/repository.go
> +	"github.com/bmstu-iu9/ptp2022-8-todo-list/backend/internal/log"
да, работает

2022-09-11 12:55 UTC, stewkk requested changes
Такая реализация фильтров мне нравится намного больше!

2022-09-11 12:55 UTC, stewkk commented on backend/internal/db/db.go
> +CREATE TYPE states AS ENUM ('equipped','inventoried','store');
```suggestion
CREATE TYPE states AS ENUM ('equipped', 'inventoried', 'store');
```

2022-09-11 12:55 UTC, stewkk commented on backend/internal/entity/item.go
> +	Unknown ItemState = ""
А состояние `Unknown` вообще бывает? =)

2022-09-11 12:55 UTC, stewkk commented on backend/internal/items/api.go
> +}
В данной реализации фильтры опциональные?

И, если да, то может лучше использовать `[]string{}`, как обозначение отсутствия фильтра?

2022-09-11 12:55 UTC, stewkk commented on backend/internal/items/repository.go
> +func makeStringForSql(filterParams []string) string {
Название так себе =)

2022-09-11 12:55 UTC, stewkk commented on backend/internal/items/repository.go
> +          (`+makeStringForSql(filters.RarityFilter)+`) AND item_category IN
Кажется, так делать небезопасно

Попробуй:
```
($1) AND item_category IN
...
..., makeStringForSql(...), usedId)
```

2022-09-11 12:55 UTC, stewkk commented on backend/internal/users/service.go
> +	err = s.repo.CleanUserInventory(id)
Умно

2022-09-11 12:58 UTC, OkDenAl commented on backend/internal/items/repository.go
> +          (`+makeStringForSql(filters.RarityFilter)+`) AND item_category IN
пробовал, так не работает

2022-09-11 13:01 UTC, stewkk commented on backend/internal/items/repository.go
> +          (`+makeStringForSql(filters.RarityFilter)+`) AND item_category IN
А [вот это](https://pkg.go.dev/database/sql#NamedArg) пробовал?

2022-09-11 13:04 UTC, stewkk commented on backend/internal/items/repository.go
> +          (`+makeStringForSql(filters.RarityFilter)+`) AND item_category IN
> А [вот это](https://pkg.go.dev/database/sql#NamedArg) пробовал?

А, не, это бесполезно

2022-09-11 14:09 UTC, OkDenAl commented on backend/internal/entity/item.go
> +	Unknown ItemState = ""
кста нет )

2022-09-12 10:30 UTC, stewkk requested changes
Надеюсь, это последняя итерация.

2022-09-12 10:30 UTC, stewkk commented on backend/internal/items/api.go
> +		return fmt.Errorf("%w: %v", errors.ErrNotFound, err)
Так тут теперь добавилась валидация, поэтому надо перенести оборачивание ошибки в сервис. Иначе, вместо ошибки валидации, у тебя возвращается 404.

2022-09-12 10:33 UTC, stewkk commented
А еще, мне все-таки не очень нравится такая реализация enum. Потому что, при изменении набора состояний, должна изменяться и их валидация, что неочевидно. К тому же, в текущем состоянии юнит-тесты не отловят такую ошибку. К слову, юнит-тесты хорошо было бы переделать под TDT.

2022-09-12 10:35 UTC, stewkk commented
> А еще, мне все-таки не очень нравится такая реализация enum. Потому что при изменении набора состояний должна изменяться и их валидация, что неочевидно. К тому же, в текущем состоянии юнит-тесты не отловят такую ошибку.
> 
> P.S. юнит-тесты хорошо было бы переделать под TDT.

Но на это можно забить =)

2022-09-14 14:04 UTC, stewkk approved these changes

2022-09-14 14:15 UTC, uma-op approved these changes
Норм

2022-09-14 14:19 UTC, geogreck approved these changes
Чётко

2022-09-14 14:41 UTC, merged