Создание инвентаря
bmstu-iu9/ptp2022-8-todo-list pull request #68
Opened 2022-08-03 16:31 UTC by Tanya-g99

2022-08-04 13:42 UTC, geogreck commented on frontend/html/inventory.html
> +                          -->
Видимо @VyacheslavIsWorkingNow не знает, что в наше время существуют специальные приложения, созданные для обмена сообщениями. Например, бумажные стаканчики

2022-08-04 14:01 UTC, VyacheslavIsWorkingNow commented on frontend/html/inventory.html
> +                          -->
хехе
Вообще, надо было это перенести отсюда в лс или issue, ты прав)

2022-08-04 14:03 UTC, VyacheslavIsWorkingNow commented on frontend/html/inventory.html
> +                        <!--                             Этот блок удалить, пока только как пример-->
вроде мой комментарий, немного запутался)

2022-08-04 14:06 UTC, VyacheslavIsWorkingNow approved these changes, later dismissed
Татьяна, отличная работа!

2022-08-04 14:19 UTC, geogreck requested changes
Красивый инвентарь, но стиль и структуру кода можно улучшить

2022-08-04 14:19 UTC, geogreck commented on frontend/html/inventory.html
> +</html>
Нет перехода на новую строку в конце файла!

2022-08-04 14:19 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +function equipped(item: Item) {
Не очень красивое и внятное название функции

2022-08-04 14:19 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +    else if (item.category === 'pet') Equipped.pet = item.id
Это лучше записать с помощью оператора `switch ... case`

2022-08-04 14:19 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +    else {
И тут

2022-08-04 14:19 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +    else return Equipped.skin
И тут

2022-08-04 14:19 UTC, geogreck commented on frontend/js/inventory/item.ts
> +    else if (rarity === 'epic') return "#f04dff"
Это лучше сделать с помощью `Map`

2022-08-04 14:19 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +function equipHTML(item: Item, unEquip: boolean = false) {
Лучше назвать функцию как-нибудь по-другому.

2022-08-04 14:19 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +    else btn.innerHTML = 'Снять'
Это красивее переписать с помощью тернарного оператора

2022-08-05 07:43 UTC, geogreck commented on frontend/js/inventory/item.ts
> +type Item = {
Кстати этот файл лучше переместить в папку utility или даже внешнюю папку, т.к. предмет не является уникальным типом для инвентаря и ещё может использоваться в магазине и профиле (?)

2022-08-05 07:46 UTC, geogreck commented on frontend/js/inventory/item.ts
> +    if (rarity === "common") return "#C8C8C8"
И естественно тогда лучше поменять название этой функции на что-нибудь по типу `getRarityColor`

2022-08-08 08:20 UTC, geogreck commented on frontend/js/inventory/item.ts
> +type Category = 'helmet' | 'chest' | 'leggins' | 'boots' | 'weapon' | 'pet' | 'skin'
А здесь то поменять забыли

2022-08-08 09:47 UTC, geogreck requested changes
Нужно починить.

2022-08-08 09:47 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +// получение предметов с сервера
```suggestion

// получение предметов с сервера
```

2022-08-08 09:47 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +// Общая обработка кликов по странице
```suggestion

// Общая обработка кликов по странице
```

2022-08-08 09:47 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +})
```suggestion

})
```

2022-08-08 09:47 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +}
```suggestion

}
```

2022-08-08 09:47 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +// добавление айди предмета item в хранилище айди надетых предметов
```suggestion

// добавление айди предмета item в хранилище айди надетых предметов
```

2022-08-08 09:47 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +// удаление предмета нужной категории из хранилища айди надетых предметов
```suggestion

// удаление предмета нужной категории из хранилища айди надетых предметов 
```

2022-08-08 09:47 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +// функция надевания
```suggestion

// функция надевания
```

2022-08-08 09:47 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +}
```suggestion

}
```

2022-08-08 09:47 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +// получение айди надетого предмета нужной категории
```suggestion

// получение айди надетого предмета нужной категории
```

2022-08-08 09:47 UTC, geogreck commented on frontend/js/inventory/inventory.ts
> +}
```suggestion

}
```

2022-08-08 09:59 UTC, geogreck approved these changes
Красиво
![image](https://user-images.githubusercontent.com/74151984/183392616-ae5dbc66-e829-4620-bcff-5da7bd99844f.png)

2022-08-08 10:00 UTC, merged