Доработка контракта API
bmstu-iu9/ptp2022-8-todo-list pull request #85
Opened 2022-09-06 13:25 UTC by stewkk

Closes #57, closes #84

2022-09-10 09:46 UTC, stewkk commented
Не хватает методов для экипировки предмета и обратного действия.

2022-09-10 09:49 UTC, geogreck commented
> Не хватает методов для экипировки предмета и обратного действия.

Почему это не просто патч запрос с полем state предмета?

2022-09-10 10:58 UTC, stewkk commented
> 



> > Не хватает методов для экипировки предмета и обратного действия.
> 
> Почему это не просто патч запрос с полем state предмета?

В текущей версии:
- POST /items/{id}/buy: store -> inventoried
- PATCH /items/{id}: inventoried -> equipped
- PATCH /items/{id}: equipped -> inventoried

При этом, запрещены:
- PATCH /items/{id}: store -> inventoried
- PATCH /items/{id}: store -> equipped
- PATCH /items/{id}: inventoried -> store
- PATCH /items/{id}: equipped -> store
Все это требует

Поэтому, считаю более наглядной такую схему:
- POST /items/{id}/buy: store -> inventoried
- POST /items/{id}/equip: inventoried -> equipped
- POST /items/{id}/unequip: equipped -> inventoried
Она отражает все возможные действия без дополнительной документации. Позволяет избежать практически бесполезный PATCH запрос, который изменяет только одно поле, и при этом с большими ограничениями.

2022-09-18 21:34 UTC, geogreck requested changes
Ну и ну!

2022-09-18 21:34 UTC, geogreck commented on docker-compose.dev.yml
> +    image: nginx:stable
Гордость!

2022-09-18 21:34 UTC, geogreck commented on docs/openapi.yml
> +          readOnly: true
Категория это тоже enum

2022-09-18 21:34 UTC, geogreck commented on docs/openapi.yml
> +          enum: [common, rare, epic, legendary]
Ещё есть `mythical` редкость предметов

2022-09-18 21:56 UTC, geogreck requested changes

2022-09-18 21:56 UTC, geogreck commented on docs/openapi.yml
> +          enum: [armor, weapon, pet, skin]
Красивые категории, да неполные, категории armor нет, есть категории helmet, chest, leggins, boots

2022-09-18 21:56 UTC, stewkk commented on docs/openapi.yml
> +          enum: [armor, weapon, pet, skin]
А ведь я посмотрел реализацию бэкенда =)))))

2022-09-18 21:57 UTC, geogreck commented on docs/openapi.yml
> +          enum: [armor, weapon, pet, skin]
Жду issue исправить операции с предметами

2022-09-18 21:58 UTC, geogreck commented on docs/openapi.yml
> +          enum: [armor, weapon, pet, skin]
Вообще рекомендую все поля проверять здесь :)
https://json.grechkogv.ru/items

2022-09-18 22:01 UTC, geogreck requested changes
VI KA

2022-09-18 22:01 UTC, geogreck commented on docs/openapi.yml
> +        imageSrc:
Не хватает `imageForHero`

2022-09-18 22:03 UTC, geogreck requested changes
Фигня, давай по новой

2022-09-18 22:04 UTC, geogreck approved these changes

2022-09-18 22:04 UTC, merged