Починил меню в магазине
bmstu-iu9/ptp2022-8-todo-list pull request #87
Opened 2022-09-06 15:35 UTC by geogreck

2022-09-06 15:38 UTC, t1d333 submitted a review, later dismissed

2022-09-06 15:39 UTC, Tanya-g99 submitted a review, later dismissed
Вы прислали решение Татьяны Гнатенко

2022-09-06 15:40 UTC, VyacheslavIsWorkingNow approved these changes, later dismissed

2022-09-06 15:41 UTC, geogreck commented
Спасибо, друзья, за вашу экспертную оценку!

2022-09-06 15:41 UTC, VyacheslavIsWorkingNow commented
😄

2022-09-06 15:46 UTC, stewkk requested changes
Есть вопросы по форматированию кода!

2022-09-06 15:46 UTC, stewkk commented on frontend/html/inventory.html
> +    <div class="body-inv body h-100">
```suggestion

    <div class="body-inv body h-100">
```

2022-09-08 18:38 UTC, geogreck commented on frontend/html/inventory.html
> +    <div class="body-inv body h-100">
Есть вопросы по месту вашего проживания!

2022-09-08 19:14 UTC, stewkk approved these changes

2022-09-08 19:14 UTC, merged